// window.x = 2;

window.Pop = [{
    id: 100, discNumber: 1, name: "Have A Nice Day", artist: "World Order", description : "See how the crew unleashes itself in Akihabara. If you need an afternoon pick-me-up or just want to put a smile on your face.", price: 10.99, inStock: true, catagories: "Pop", imageUrl:'./assets/img/Pop/WORLD ORDER - HAVE A NICE DAY.jpeg', audio: './assets/audio/Pop/WORLD ORDER - HAVE A NICE DAY.mp3', releaseDate: "17/Dec/2014", length: "4:34", rating: "⭐⭐⭐⭐", ratingNumber: 4, artistUrl: "https://www.worldorder-fansite.com/"
},{
    id: 101, discNumber: 2, name: "Everwhite", artist: "Hatsune Miku", description : "\"Everwhite\" is an original song by MinisukaP featuring Hatsune Miku. The song has reached the Hall of Fame.", price: 12.99, inStock: true, catagories: "Pop", imageUrl:'./assets/img/Pop/Hatsune Miku - Everwhite.jpeg', audio: './assets/audio/Pop/Hatsune Miku - Everwhite.mp3', releaseDate: "27/Jan/2008", length: "6:14", rating: "⭐⭐⭐⭐⭐", ratingNumber: 5, artistUrl: "https://mikuexpo.com/"
},{
    id: 102, discNumber: 3, name: "Demons", artist: "Imagine Dragons", description : "\"Demons\" is a song by American rock band Imagine Dragons", price: 15.99, inStock: true, catagories: "Pop", imageUrl:'./assets/img/Pop/Imagine Dragons - Demons.jpeg', audio: './assets/audio/Pop/Imagine Dragons - Demons.mp3'  , releaseDate: "28/Jan/2013", length: "2:56", rating: "⭐⭐⭐⭐", ratingNumber: 4, artistUrl: "https://www.imaginedragonsmusic.com/"
},{
    id: 103, discNumber: 4, name: "Celestial Symphony", artist: "Hatsune Miku", description : "Original Upload Date March 22, 2008", price: 5.99, inStock: true, catagories: "Pop", imageUrl:'./assets/img/Pop/Hatsune Miku - Celestial Symphony.jpeg', audio: './assets/audio/Pop/Hatsune Miku - Celestial Symphony.mp3' , releaseDate: "21/Mar/2008", length: "5:23", rating: "⭐⭐⭐⭐⭐", ratingNumber: 5, artistUrl: "https://mikuexpo.com/"
},{
    id: 104, discNumber: 5, name: "Just A Dream", artist: "Nelly", description : "Nelly said, \"I think that the way the whole song plays out, with the beat and the lyrics, I think it comes together in the sense of it's almost a timeless song.\"", price: 13.99, inStock: true, catagories: "Pop", imageUrl:'./assets/img/Pop/Nelly - Just A Dream.jpeg', audio: './assets/audio/Pop/Nelly - Just A Dream.mp3' , releaseDate: "16/Aug/2010", length: "4:02", rating: "⭐⭐⭐⭐⭐", ratingNumber: 5, artistUrl: "http://www.nelly.net/"
}]

window.Rock = [{
    id: 200, discNumber: 1, name: "Crawling In The Dark", artist: "Hoobastank", description : "\"Crawling in the Dark\" is the first single by the American rock band Hoobastank.", price: 6.99, inStock: true, catagories: "Rock", imageUrl:'./assets/img/Rock/Crawling_In_The_Dark_by_Hoobastank.jpg', audio: './assets/audio/Rock/Hoobastank - Crawling In The Dark.mp3', releaseDate: "02/Oct/2001", length: "2:55", rating: "⭐⭐⭐⭐⭐",ratingNumber: 5, artistUrl: "https://hoobastank.com/"
},{
    id: 201, discNumber: 2, name: "Bullet for my Valentine", artist: "Hand of Blood", description : "Hand of Blood is the second EP by Welsh heavy metal band Bullet for My Valentine, released on 22 August 2005 through Trustkill Records.", price: 7.99, inStock: true, catagories: "Rock", imageUrl:'./assets/img/Rock/Bullet_For_My_Valentine.jpg', audio: './assets/audio/Rock/Bullet For My Valentine - Hand of blood.mp3', releaseDate: "02/Aug/2005", length: "3:35", rating: "⭐⭐⭐⭐⭐", ratingNumber: 5, artistUrl: "https://bulletformyvalentine.com/"
},{
    id: 202, discNumber: 3, name: "Beginning of the End", artist: "Spineshank", description : "Spineshank was an American nu metal band from Los Angeles.", price: 10.99, inStock: true, catagories: "Rock", imageUrl:'./assets/img/Rock/Spineshank.jpg', audio: './assets/audio/Rock/Beginning of the End - Spineshank.mp3', releaseDate: "09/Sep/2003", length: "3:32", rating: "⭐⭐⭐⭐⭐", ratingNumber: 5, artistUrl: "https://en.wikipedia.org/wiki/Spineshank"
},{
    id: 203, discNumber: 4, name: "The Quiet Place", artist: "In Flames", description : "\"The Quiet Place\" is a song by Swedish heavy metal band In Flames.", price: 8.99, inStock: true, catagories: "Rock", imageUrl:'./assets/img/Rock/In_Flames.jpg', audio: './assets/audio/Rock/The Quiet Place - In Flames.mp3', releaseDate: "01/Mar/2004", length: "3:45", rating: "⭐⭐⭐⭐⭐", ratingNumber: 5, artistUrl: "https://www.inflames.com/"
},{
    id: 204, discNumber: 5, name: "Angels of Clarity", artist: "Dead By April", description : "Angels of Clarity is a track by Dead by April on their eponymous debut album. It was written by Pontus Hjelm and Jimmie Strimell.", price: 11.99, inStock: true, catagories: "Rock", imageUrl:'./assets/img/Rock/Dead_By_April.jpg', audio: './assets/audio/Rock/Angels of Clarity - Dead by April.mp3', releaseDate: "28/Sep/2009", length: "3:42", rating: "⭐⭐⭐⭐⭐", ratingNumber: 5, artistUrl: "https://www.deadbyapril.com/"
}]
window.Ninetys = [{
    id: 300, discNumber: 1, name: "My Love", artist: "Westlife", description : "\"My Love\" is a song by Irish boy band Westlife.", price: 20.99, inStock: true, catagories: "Ninetys", imageUrl:'./assets/img/Ninteys/Westlife - My Love.jpeg', audio: './assets/audio/Ninteys/Westlife - My Love.mp3', releaseDate: "20/Oct/2000", length: "4:23", rating: "⭐⭐⭐⭐", ratingNumber: 4, artistUrl: "https://www.westlife.com/"
},{
    id: 301, discNumber: 2, name: "I'm a dreamer", artist: "Maaya Sakamoto", description : "Platinum (プラチナ, Purachina) is the opening song to the third season of Cardcaptor Sakura , sung by Maaya Sakamoto.", price: 30.99, inStock: true, catagories: "Ninetys", imageUrl:'./assets/img/Ninteys/Maaya Sakamoto - Im a dreamer.jpeg', audio: './assets/audio/Ninteys/Maaya Sakamoto - Im a dreamer.mp3', releaseDate: "21/Oct/1999", length: "4:13", rating: "⭐⭐⭐⭐⭐", ratingNumber: 5, artistUrl: "https://www.jvcmusic.co.jp/maaya/"
},{
    id: 302, discNumber: 3, name: "Its My Life", artist: "Bon Jovi", description : "\"It's My Life\" is a song by American rock band Bon Jovi.", price: 17.99, inStock: true, catagories: "Ninetys", imageUrl:'./assets/img/Ninteys/Bon Jovi - Its My Life.jpeg', audio: './assets/audio/Ninteys/Bon Jovi - Its My Life.mp3' ,releaseDate: "23/May/2000", length: "4:27", rating: "⭐⭐⭐⭐⭐", ratingNumber: 5, artistUrl: "https://www.bonjovi.com/"
},{
    id: 303, discNumber: 4, name: "I Want It That Way", artist: "Backstreet Boys", description : "I Want it That Way is a real-life song created by the Backstreet Boys in 1999.", price: 10.99, inStock: true, catagories: "Ninetys", imageUrl:'./assets/img/Ninteys/Backstreet Boys - I Want It That Way.jpeg', audio: './assets/audio/Ninteys/Backstreet Boys - I Want It That Way.mp3', releaseDate: "12/Apr/1999", length: "3:39", rating: "⭐⭐⭐⭐", ratingNumber: 4, artistUrl: "https://backstreetboys.com/"
},{
    id: 304, discNumber: 5, name: "Poison", artist: "Alice Cooper", description : "\"Poison\" is a song by American musician Alice Cooper. Written by Cooper", price: 10.99, inStock: false, catagories: "Ninetys", imageUrl:'./assets/img/Ninteys/Alice Cooper - Poison.jpeg', audio: './assets/audio/Ninteys/Alice Cooper - Poison.mp3', releaseDate: "17/Jul/1989", length: "4:28", rating: "⭐⭐⭐", ratingNumber: 3, artistUrl: "https://alicecooper.com/"
}]
window.Soundtracks = [{
    id: 400, discNumber: 1, name: "Sleepless", artist: "Nyte", description : "Sleepless by Nyte.", price: 3.99, inStock: true, catagories: "Soundtracks", imageUrl:'./assets/img/Soundtracks/Nyte - Sleepless.jpeg', audio: './assets/audio/Soundtracks/Nyte - Sleepless.mp3', releaseDate: "14/Jun/2016", length: "4:29", rating: "⭐⭐⭐⭐", ratingNumber: 4, artistUrl: "https://open.spotify.com/artist/5FAjeD9eW52qvpik9OsnVp"
},{
    id: 401, discNumber: 2, name: "Dreams", artist: "Ahrix", description : "Ahrix grew up with his parents in Netherlands and was a successful student who loves music.", price: 4.99, inStock: true, catagories: "Soundtracks", imageUrl:'./assets/img/Soundtracks/Ahrix - Dreams.jpeg', audio: './assets/audio/Soundtracks/Ahrix - Dreams.mp3', releaseDate: "17/Jul/1989", releaseDate: "24/Apr/2015", length: "3:22", rating: "⭐⭐⭐", ratingNumber: 3, artistUrl: "https://lnk.bio/ahrix"
},{
    id: 402, discNumber: 3, name: "Infectious", artist: "Tobu", description : "A 2014 track by Lativan producer Tobu.", price: 5.99, inStock: true, catagories: "Soundtracks", imageUrl:'./assets/img/Soundtracks/Tobu - Infectious.jpeg', audio: './assets/audio/Soundtracks/Tobu - Infectious.mp3', releaseDate: "2/Jun/2014", length: "4:16", rating: "⭐⭐⭐⭐", ratingNumber: 4, artistUrl: "https://tobumusic.com/"
},{
    id: 403, discNumber: 4, name: "Imaginary Friends", artist: "Laszlo", description : "Imaginary Friends is one of the few 2013 NCS YouTube videos not removed from the channel.", price: 13.99, inStock: true, catagories: "Soundtracks", imageUrl:'./assets/img/Soundtracks/Laszlo - Imaginary Friends.jpeg', audio: './assets/audio/Soundtracks/Laszlo - Imaginary Friends.mp3', releaseDate: "26/Dec/2013", length: "5:53", rating: "⭐⭐⭐⭐⭐", ratingNumber: 5, artistUrl: "https://nocopyrightsounds.fandom.com/wiki/Laszlo"
},{
    id: 404, discNumber: 5, name: "Dancing Christmas", artist: "Ragnarok Online", description : "Ragnarok Online OST 85.", price: 7.99, inStock: true, catagories: "Soundtracks", imageUrl:'./assets/img/Soundtracks/Ragnarok Online - Dancing Christmas in the 13th Month.jpeg', audio: './assets/audio/Soundtracks/Ragnarok Online - Dancing Christmas in the 13th Month.mp3', releaseDate: "26/Aug/2009", length: "3:05", rating: "⭐⭐⭐", ratingNumber: 3, artistUrl: "http://iro.ragnarokonline.com/"
}]